// Fetches the Tesla Roadster's path from JPL Horizons (object -143205) and writes src/objects/s0-roadster-data.js.
// Heliocentric state vectors, ICRF (J2000 equatorial), AU and AU/day, every 40 days from 2018-02-08 to 2070.
// Then checks the page's interpolation (cubic Hermite between rows) against Horizons' own positions a week apart in the current year.
//   node tools/roadster.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const H = 40, START = '2018-02-08', STOP = '2070-01-01';
async function vectors(start, stop, step){
  const q = new URLSearchParams({ format:'text', COMMAND:"'-143205'", EPHEM_TYPE:'VECTORS', CENTER:"'500@10'", REF_PLANE:'FRAME', START_TIME:`'${start}'`, STOP_TIME:`'${stop}'`,
    STEP_SIZE:`'${step}'`, VEC_TABLE:'2', OUT_UNITS:'AU-D', CSV_FORMAT:'YES' });
  const r = await fetch('https://ssd.jpl.nasa.gov/api/horizons.api?' + q);
  if (!r.ok) throw new Error('Horizons answered ' + r.status);
  const t = await r.text(), body = t.split('$$SOE')[1];
  if (!body) throw new Error('no table in the answer:\n' + t.slice(0, 2000));
  const sol = (t.match(/solution #(\d+)/) || [])[1];
  return { sol, rows:body.split('$$EOE')[0].trim().split('\n').map(l => { const c = l.split(','); return [+c[0], ...c.slice(2, 8).map(Number)]; }) };
}
const { sol, rows } = await vectors(START, STOP, H + ' d');
const jd0 = rows[0][0];
rows.forEach((r, i) => { if (Math.abs(r[0] - (jd0 + i*H)) > 1e-6) throw new Error('uneven step at row ' + i); });
const enc = rows.map(r => [...r.slice(1, 4).map(x => Math.round(x*1e8)), ...r.slice(4, 7).map(x => Math.round(x*1e10))].map(n => n.toString(36)).join(',')).join(';');
// the same interpolation as the page (roadsterEq in s1-roadster.js)
const D = enc.split(';').map(r => r.split(',').map(s => parseInt(s, 36)));
function at(jd){ const x = (jd - jd0)/H, i = Math.min(Math.max(Math.floor(x), 0), D.length - 2), s = x - i, a = D[i], b = D[i + 1];
  const h00 = 2*s**3 - 3*s*s + 1, h10 = s**3 - 2*s*s + s, h01 = -2*s**3 + 3*s*s, h11 = s**3 - s*s;
  return [0, 1, 2].map(k => (h00*a[k] + h01*b[k])*1e-8 + (h10*a[k + 3] + h11*b[k + 3])*H*1e-10); }
const y = new Date().getUTCFullYear(), chk = await vectors(`${y}-01-01`, `${y}-12-31`, '7 d');
let err = 0; for (const r of chk.rows){ const p = at(r[0]); err = Math.max(err, Math.hypot(p[0] - r[1], p[1] - r[2], p[2] - r[3])); }
const out = `// generated by tools/roadster.mjs from JPL Horizons (object -143205, JPL solution ${sol}) on ${new Date().toISOString().slice(0, 10)}: do not edit by hand.
// One row every ${H} days from JD ${jd0} (${START}): x, y, z in 1e-8 AU and vx, vy, vz in 1e-10 AU/day, heliocentric ICRF, base 36.
const ROADSTER_DATA = { jd0:${jd0}, h:${H}, rows:'${enc}' };
`;
fs.writeFileSync(path.join(ROOT, 'src', 'objects', 's0-roadster-data.js'), out);
console.log(`${rows.length} rows (${enc.length} characters), solution ${sol}; interpolation within ${Math.round(err*149597870.7).toLocaleString('en-US')} km of Horizons in ${y}`);
